# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: echo "my first hello"

jobs:
  two:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: echo "my second hello"

workflow:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
