# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/tea-shops
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Install rspec
          command: gem install rspec

  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: echo "my second hello"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          require: build

